### ISSUE TITLE
Maven doesn't work correctly in QEMU arm/v7 maven:adoptopenjdk

### ISSUE THREAD

**Issue by BretFisher** [carlossg/docker-maven#213]
Trying to run `mvn -v` on `linux/arm/v7` results in `java.lang.ClassNotFoundException: org.apache.maven.cli.MavenCli`

```
 ➜ docker run -it --platform linux/arm/v7 maven:adoptopenjdk bash
Unable to find image 'maven:adoptopenjdk' locally
adoptopenjdk: Pulling from library/maven
Digest: sha256:d12319a2437e4caa219e876d7d6ec4927199c8206bd0e7432dce2c6d7e5ddbf1
Status: Downloaded newer image for maven:adoptopenjdk
root@ef1c77fc0537:/# mvn -v
java.lang.ClassNotFoundException: org.apache.maven.cli.MavenCli
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:140)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:259)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

Doing the same on arm64 works:
```
 ➜ docker run -it --platform linux/arm64 maven:adoptopenjdk bash 
Unable to find image 'maven:adoptopenjdk' locally
adoptopenjdk: Pulling from library/maven
Digest: sha256:d12319a2437e4caa219e876d7d6ec4927199c8206bd0e7432dce2c6d7e5ddbf1
Status: Downloaded newer image for maven:adoptopenjdk
root@41007ac099af:/# mvn -v
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/share/maven
Java version: 15.0.2, vendor: AdoptOpenJDK, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.25-linuxkit", arch: "aarch64", family: "unix"```

**Comment by carlossg** [comment]
unfortunately I don't have access to an ARM box to test

**Comment by BretFisher** [comment]
If you have Docker Desktop (mac or windows) and run that command, it'll use QEMU to emulate arm64 and arm/v7 (32bit).

I did some more testing and it looks like it's only in QEMU that this issue shows up. Let me see if I can get someone with more skills in Java + QEMU to weigh in before we close this.

<img width="1305" alt="Screen Shot 2021-07-02 at 6 02 42 PM" src="https://user-images.githubusercontent.com/792287/124332734-263ff080-db60-11eb-9a23-ffa9ca49dc79.png">

**Comment by BretFisher** [comment]
OK I'm going to close, and renamed for helping others find this when they try Maven in QEMU arm/v7. Thanks!

**Comment by tech-scorpio** [comment]
I am trying to build a docker image for my Raspberry Pi (armV7) from my Macbook...I get exactly the same error.  Is there a solution since the issue was closed? When you closed the ticket, did you mean that the only way to build the image was to do it directly on the target host (Rapberry Pi) ?
