### ISSUE TITLE
zookeeper maven dependency bug

### ISSUE THREAD

**Issue by divneet** [carlossg/docker-maven#33]
I'm continuously getting this bug whenever i try to run the zookeeper client code i get an error .  
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException

any help would be appreciated .

**Comment by carlossg** [comment]
You should ask in the zookeeper mailing list

**Comment by divneet** [comment]
well for some reason the same code runs build using intellij  & the problem  persists if build & run the code using the maven docker image .

**Comment by divneet** [comment]
$ docker run -it --rm -v "$PWD":/zk -w /zk maven:3.5-jdk-8 java -cp target/zk-crud-1.0-SNAPSHOT.jar com.datreon.zk.App


Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.KeeperException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by carlossg** [comment]
what are the contents of zk-crud-1.0-SNAPSHOT.jar ?
